repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.5  
    hooks:
      - id: ruff
        args: [--fix]
        files: ^space2stats_api/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1   
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        files: ^space2stats_api/
        exclude: ^space2stats/env/

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: bash -c 'PYTHONPATH=space2stats_api python -m pytest space2stats_api'
        language: system
        pass_filenames: false
        always_run: true