repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python
        args: ["-m", "3", "--trailing-comma", "-l", "88"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix]
        files: ^space2stats_api/
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]  # You can adjust this as needed
        files: ^space2stats_api/
        exclude: ^space2stats/env/
        additional_dependencies:
          - types-requests
  
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.7
    hooks:
      - id: nbqa-ruff
        args: ["--fix"]
        # Match all `.ipynb` files under `notebooks/user-docs/`
        files: ^notebooks/user-docs/.*\.ipynb$
      - id: nbqa-isort
        args: ["--profile=black"]
        additional_dependencies: [isort==5.6.4]
        # Match all `.ipynb` files under `notebooks/user-docs/`
        files: ^notebooks/user-docs/.*\.ipynb$
      - id: nbqa-black
        # Match all `.ipynb` files under `notebooks/user-docs/`
        files: ^notebooks/user-docs/.*\.ipynb$
      - id: nbqa-pyupgrade
        args: ["--py37-plus"]
        # Match all `.ipynb` files under `notebooks/user-docs/`
        files: ^notebooks/user-docs/.*\.ipynb$