repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.5  
    hooks:
      - id: ruff
        args: [--fix]
        files: ^space2stats_api/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1   
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        files: ^space2stats_api/
        exclude: ^space2stats/env/
