version: '3'

services:
  database:
    platform: linux/amd64
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - 5439:5432
    command: >
      postgres -N 500
      -c max_wal_size=2GB
      -c checkpoint_timeout=30min
      -c synchronous_commit=off
      -c wal_level=minimal
      -c maintenance_work_mem=256MB
      -c max_wal_senders=0
    volumes:
      - ./.pgdata:/var/lib/postgresql/data