version: '3'

services:
  database:
    # at time of writing this, ARM64 is not supported so we make sure to use
    # a supported platform: https://github.com/postgis/docker-postgis/issues/216
    # Could possibly switch to https://github.com/vincentsarago/containers
    platform: linux/amd64
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - 5439:5432
    command: postgres -N 500
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
