# Book settings
title: DECAT Space2Stats
author: World Bank
logo: images/logo.png
only_build_toc_files: true

repository:
  url: https://github.com/worldbank/DECAT_Space2Stats
  branch: main

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: true
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: false
  baseurl: https://github.com/worldbank/DECAT_Space2Stats
  extra_footer: |
    <div>
        <b>All content (unless otherwise specified) is subject to the <a href="https://raw.githubusercontent.com/worldbank/template/main/LICENSE">World Bank Master Community License Agreement.</a></b>
    </div>
#######################################################################################
# Execution settings
execute:
  execute_notebooks: off

#######################################################################################
# Sphinx settings
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"
    apidoc_module_dir: ../space2stats_client/src
    extra_extensions:
      - sphinx.ext.autodoc
      - sphinx.ext.napoleon