name: Client Release

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./space2stats_client

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
        
      - name: Install dependencies
        run: |
          poetry install --with test

      - name: Run tests
        run: poetry run pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./space2stats_client

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
        
      - name: Install dependencies
        run: |
          poetry install

      - name: Build package
        run: poetry build

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/') # only publish to PyPI on tag pushes
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/space2stats-client/
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: ./space2stats_client

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
        
      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

