name: Client Release

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./space2stats_client

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        
      - name: Install dependencies
        run: |
          poetry run pip install --upgrade pip setuptools wheel
          poetry run pip install cython numpy
          poetry install --with test

      - name: Run tests
        run: poetry run pytest

  publish:
    needs: test
    if: startsWith(github.ref, 'refs/tags/') # only publish to PyPI on tag pushes
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/space2stats-client/
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: ./space2stats_client

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        
      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

