name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      stage: 
        type: string
        required: true

jobs:
  build:
    concurrency: ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::017820688988:role/Space2Stats-Deploy-Role
          aws-region: ${{ vars.CDK_DEFAULT_REGION }}
    
      - name: Install CDK dependencies
        working-directory: ./space2stats_api/cdk
        run: |
          pip install -r requirements-cdk.txt 

      - name: Deploy CDK stack to staging
        working-directory: ./space2stats_api/cdk
        env:
            STAGE: ${{ inputs.stage }}
            PGHOST: ${{ secrets.PGHOST }}
            PGPORT: ${{ secrets.PGPORT }}
            PGDATABASE: ${{ secrets.PGDATABASE }}
            PGUSER: ${{ secrets.PGUSER }}
            PGPASSWORD: ${{ secrets.PGPASSWORD }}
            PGTABLENAME: ${{ secrets.PGTABLENAME }}
            CDK_CERTIFICATE_ARN: ${{ vars.CDK_CERTIFICATE_ARN }}  
            CDK_DEFAULT_ACCOUNT: ${{ vars.CDK_DEFAULT_ACCOUNT }}  
            CDK_DEFAULT_REGION: ${{ vars.CDK_DEFAULT_REGION }}
            CDK_DOMAIN_NAME: ${{ vars.CDK_DOMAIN_NAME }} 
        run: cdk deploy --require-approval never
