name: Deploy to appropriate environment

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  deploy-to-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    uses: "./.github/workflows/reusable-deploy.yml"
    with:
      environment: Space2Stats API Dev
      stage: pr-${{ github.event.pull_request.number }}
      pr-number: ${{ github.event.pull_request.number }}
    secrets: inherit

  deploy-to-production:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.ref_name == 'main' }}
    uses: "./.github/workflows/reusable-deploy.yml"
    with:
      environment: Space2Stats API Prod
      stage: prod
    secrets: inherit
