name: Publish to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install Dependencies
        working-directory: space2stats_api/src
        run: |
          if [ -f pyproject.toml ]; then
            pip install poetry && poetry install --with docs
          fi
      - name: Build Jupyter Book using Sphinx
        run: |
          source $(poetry env info --path)/bin/activate
          sphinx-build docs _build/html -b html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: job.status == 'success'
        with:
          path: "_build/html"

  deploy-book:
    needs: build-book
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4